### ISSUE TITLE
Structure file into sections

### ISSUE THREAD

**Issue by tillgrallert** [tillgrallert/diwan-al-rusafi#3]
The book is organised in sections, which should be transcribed as 

```xml
<div type="section">
    <head>section title</head>
    <div type="item" subtype="verse">
        <head>qaṣīda title</head>
        <!-- ... -->
    </div>
    <div type="item" subtype="verse">
        <head>qaṣīda title</head>
        <!-- ... -->
    </div>
</div>
```

**Comment by Jkoeppens** [comment]
das verstehe ich als Aufgabe nicht, von der Logik allerdings schon. Also es gibt unterschiedliche div, das ist die Baumstruktur, jeweils ist das dann eine Überschrift. Aber die sind doch drin, oder nicht?
